### ISSUE TITLE
Cannot start up db container - permission denied for writing log file

### ISSUE THREAD

**Issue by ainsofs** [keensoft/docker-alfresco#1]
When viewing the db logs with `docker-compose logs -f db` I see

`postgres       | 2018-12-13 20:20:29.230 UTC [1] FATAL:  could not open log file "/var/log/postgresql/postgresql-2018-12-13_202029.log": Permission denied`
`postgres       | 2018-12-13 20:20:29.232 UTC [1] LOG:  database system is shut down`
`postgres exited with code 1`

I tried setting the repo ownership to user 1000 and for volume/data/solr-data to user 1001 but no change. Am I missing something?

I am using Ubuntu 16.04 64 Bit

**Comment by angelborroy-ks** [comment]
Postgres Service is mapping logs volume at

https://github.com/keensoft/docker-alfresco/blob/master/docker-compose.yml#L103 

So probably the problem with the permissions must be fixed at `./volumes/logs/postgres`

**Comment by ainsofs** [comment]
I finally got it to work by setting the User Id of /volumes/logs/postgres to 999 (postgres user)

In summary my User Ids were

chown -R 1000:1000 .
chown -R 1001:1001 ./volumes/data/solr
chown -R 999:1000 ./volumes/logs/postgres

--
docker-compose version 1.21.0
docker version 18.03.1-ce
